# This file has been generated -- see https://github.com/hvr/multi-ghc-travis
language: c
sudo: false

cache:
  directories:
    - $HOME/.cabsnap
    - $HOME/.cabal/packages
    - $HOME/.stack

before_cache:
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.tar

env:
  global:
    secure: "C2YwYhIClWJKjKQ1AfsHn0Py5+6WkA79Ny6bfR9JxQ10aT3sq5FcZt0ZfwutK0+jQ5F6c3+L0yJaNm8dp1+0MGK0ALDE3vx9ftJkXLp/5LwSdfeHHiMLFoQsSs3mGw9DirxiHbWlDzBKNfRi397Vckh0sfEGx/rEBIs5PS86wIU="

matrix:
  include:
    - env: BUILD=cabal CABALVER=1.18 GHCVER=7.8.4
      compiler: ": #GHC 7.8.4"
      addons: {apt: {packages: [cabal-install-1.18,ghc-7.8.4], sources: [hvr-ghc]}}
    - env: BUILD=cabal CABALVER=1.22 GHCVER=7.10.3
      compiler: ": #GHC 7.10.3"
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.3], sources: [hvr-ghc]}}
    - env: BUILD=cabal CABALVER=1.24 GHCVER=8.0.1
      compiler: ": #GHC 8.0.1"
      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.1], sources: [hvr-ghc]}}

    - env: BUILD=stack STACK_YAML=stack-lts-2.yaml GHCVER=7.8.4
      compiler: ": #STACK LTS2"
      addons: {apt: {packages: [ghc-7.8.4], sources: [hvr-ghc]}}
    - env: BUILD=stack STACK_YAML=stack-lts-3.yaml GHCVER=7.10.2
      compiler: ": #STACK LTS3"
      addons: {apt: {packages: [ghc-7.10.2], sources: [hvr-ghc]}}
    - env: BUILD=stack STACK_YAML=stack-lts-4.yaml  GHCVER=7.10.3
      compiler: ": #STACK LTS4"
      addons: {apt: {packages: [ghc-7.10.3], sources: [hvr-ghc]}}
    - env: BUILD=stack STACK_YAML=stack-lts-5.yaml  GHCVER=7.10.3
      compiler: ": #STACK LTS5"
      addons: {apt: {packages: [ghc-7.10.3], sources: [hvr-ghc]}}
    - env: BUILD=stack STACK_YAML=stack-lts-6.yaml  GHCVER=7.10.3
      compiler: ": #STACK LTS6"
      addons: {apt: {packages: [ghc-7.10.3], sources: [hvr-ghc]}}
    - env: BUILD=stack STACK_YAML=stack-lts-7.yaml  GHCVER=7.10.3
      compiler: ": #STACK LTS7"
      addons: {apt: {packages: [ghc-8.0.1], sources: [hvr-ghc]}}
    - env: BUILD=stack STACK_YAML=stack-nightly.yaml GHCVER=7.10.3
      compiler: ": #STACK nightly"
      addons: {apt: {packages: [ghc-7.10.3], sources: [hvr-ghc]}}

    - env: BUILD=stack STACK_YAML=stack-lts-4.yaml
      compiler: ": #stack LTS4 OSX"
      os: osx

    - env: BUILD=stack-space-leak
      compiler: ": #STACK - space leak"
      addons: {apt: {packages: [ghc-7.10.3], sources: [hvr-ghc]}}

before_install:
  - unset CC
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.local/bin:$PATH

install:
  - sh travis-install.sh

# Here starts the actual work to be performed for the package under test;
# any command which exits with a non-zero exit code causes the build to fail.
script:
  - sh travis-script.sh

branches:
  only:
  - master

# EOF
