# NB: don't set `language: haskell` here

# See also https://github.com/hvr/multi-ghc-travis for more information
env:
 - GHCVER=7.8.4 CABALVER=1.18
 - GHCVER=7.8.4 CABALVER=1.18 STACKAGEURL=https://www.stackage.org/lts-2.22/cabal.config
 - GHCVER=7.10.2 CABALVER=1.22
 - GHCVER=7.10.2 CABALVER=1.22 STACKAGEURL=https://www.stackage.org/lts-3/cabal.config
 - GHCVER=7.10.2 CABALVER=1.22 STACKAGEURL=https://www.stackage.org/nightly/cabal.config
 - GHCVER=head CABALVER=head

matrix:
  allow_failures:
   - env: GHCVER=head CABALVER=head

# Note: the distinction between `before_install` and `install` is not
#       important.
before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 - cabal --version

install:
 - if [ -n "$STACKAGEURL" ]; then wget $STACKAGEURL; fi
 - travis_retry cabal update
 - cabal install --only-dependencies --enable-tests

# Here starts the actual work to be performed for the package under
# test; any command which exits with a non-zero exit code causes the
# build to fail.
script:
 # -v2 provides useful information for debugging
 - cabal configure -v2 --enable-tests

 # this builds all libraries and executables
 # (including tests/benchmarks)
 - cabal build
 - cabal test

 # tests that a source-distribution can be generated
 - cabal sdist

 # check that the generated source-distribution can be built & installed
 - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
   cd dist/;
   if [ -f "$SRC_TGZ" ]; then
      cabal install --force-reinstalls "$SRC_TGZ";
   else
      echo "expected '$SRC_TGZ' not found";
      exit 1;
   fi

# EOF
